events {}

http {

    upstream api_server {
        server api:8000;
    }

    upstream gradio_server {
        server gradio-ui:7860;
    }

    server {
        listen 80;

        client_max_body_size 200M;

        # ===== STATIC UPLOADS =====
        location /uploads/ {
            alias /usr/share/nginx/html/uploads/;
            autoindex off;
            add_header Cache-Control "public, max-age=31536000, immutable";
        }

        # ===== GRADIO UI =====
        location / {
            proxy_pass http://gradio_server;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        # ===== FASTAPI =====
        location /api/ {
            rewrite ^/api/(.*)$ /$1 break;
            proxy_pass http://api_server;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
